config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index show edit update destroy]
    resources :vtubers, only: %i[new create index show edit update destroy]
    resources :instruments, only: %i[new create]
    resources :members, only: %i[new create index destroy]
    resources :songs, only: %i[new create index show edit update destroy]
    resources :comments, only: %i[index destroy]
    resources :inquiries, only: %i[index show destroy] do
      member do
        post :close
      end
    end
  end

  root 'guide#about'
  resources :users, only: %i[new create show edit update]
  get '/login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'

  resources :vtubers, only: %i[show index]
  resources :songs, only: %i[new create index show edit update destroy] do
    resources :comments, only: %i[create destroy]
    resources :favorites, only: %i[create destroy]
    collection do
      get :favorites
      get :autocomplete
    end
  end
  resources :requests, only: %i[new create] do
    collection do
      post 'vtuber_form'
      post 'song_form'
      get :autocomplete
    end
  end
  
  resources :inquiries, only: %i[new create]

  get '/about', to: 'guide#about'
  get '/terms', to: 'guide#terms'
  get '/privacy_policy', to: 'guide#privacy_policy'

  resources :password_resets, only: %i[new create edit update]
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 100 }, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :content, presence: true, length: { maximum: 2000 }
end

app/controllers/admin/inquiries_controller.rb
class Admin::InquiriesController < Admin::BaseController
  before_action :set_inquiry, only: %i[show close destroy]

  def index
    @inquiries = Inquiry.all.order(created_at: :desc).page(params[:page])
  end

  def show; end

  def close
    if @inquiry.update_columns(closed_at: Time.now)
      redirect_to admin_inquiries_path, success: t('.closed_successfully')
    else
      Rails.logger.error("Failed to close inquiry. Errors: #{@inquiry.errors.full_messages}")
      flash[:danger] = t('.fail')
      redirect_to admin_inquiries_path
    end
  end

  def destroy
    @inquiry.destroy!
    redirect_to admin_inquiries_path, success: t('.success')
  end

  private
  
  def set_inquiry
    @inquiry = Inquiry.find(params[:id])
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save
      flash[:success] = t('.success')
      redirect_to inquiries_path
    else
      flash[:danger] = @inquiry.errors.full_messages
      redirect_to action: :new
    end
  end

  def index
    @inquiries = Inquiry.all.order(created_at: :desc).page(params[:page])
  end

  def show; end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :content)
  end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/admin/inquiries/_inquiry.html.erb
<tr>
  <td>
    <%= inquiry.id %>
  </td>
  <td>
    <%= inquiry.name %>
  </td>
  <td>
    <%= inquiry.email %>
  </td>
  <td>
    <%= truncate(inquiry.content, length: 20) %>
  </td>
  <td>
    <%= l inquiry.created_at, format: :long %>
  </td>
  <td>
    <% if inquiry.closed_at %>
      <%= l inquiry.closed_at, format: :long %>
    <% else %>
      <%= t('.not_closed_at') %>
    <% end %>
  </td>
  <td class="d-flex">
    <%= link_to t('defaults.show'), admin_inquiry_path(inquiry), class: 'btn btn-info' %>
    <% unless inquiry.closed_at? %>
      <%= button_to t('.close'), close_admin_inquiry_path(inquiry), method: :post, data: { turbo_confirm: t('defaults.message.close_confirm') }, class: 'btn btn-success' %>
    <% end %>
    <%= button_to t('defaults.delete'), admin_inquiry_path(inquiry), method: :delete, data: { turbo_confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/inquiries/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
            <tr>
              <th scope="col">Id</th>
              <th scope="col"><%= t('.name') %></th>
              <th scope="col"><%= t('.email') %></th>
              <th scope="col"><%= t('.content') %></th>
              <th scope="col"><%= t('.created_at') %></th>
              <th scope="col"><%= t('.closed_at') %></th>
            </tr>
            </thead>
            <tbody>
              <%= render @inquiries %>
            </tbody>
          </table>
          <div class="item__paginate">
            <%= paginate @inquiries %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/inquiries/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <div class="d-flex">
        <% unless @inquiry.closed_at? %>
          <%= button_to t('.close'), close_admin_inquiry_path(@inquiry), method: :post, data: { turbo_confirm: t('defaults.message.close_confirm') }, class: 'btn btn-success' %>
        <% end %>
        <%= button_to t('defaults.delete'), admin_inquiry_path(@inquiry), method: :delete, data: { turbo_confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row">Id</th>
          <td><%= @inquiry.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= t('.name') %></th>
          <td><%= @inquiry.name %></td>
        </tr>
        <tr>
          <th scope="row"><%= t('.email') %></th>
          <td><%= @inquiry.email %></td>
        </tr>
        <tr>
          <th scope="row"><%= t('.content') %></th>
          <td><%= @inquiry.content %></td>
        </tr>
        <tr>
          <th scope="row"><%= t('.created_at') %></th>
          <td><%= l @inquiry.created_at, format: :long %></td>
        </tr>
        <tr>
          <th scope="row"><%= t('.closed_at') %></th>
          <td>
            <% if @inquiry.closed_at %>
              <%= l @inquiry.closed_at, format: :long %>
            <% else %>
              <%= t('.not_closed_at') %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>