config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index show edit update destroy]
    resources :vtubers, only: %i[new create index show edit update destroy]
    resources :instruments, only: %i[new create]
    resources :members, only: %i[new create index destroy]
    resources :songs, only: %i[new create index show edit update destroy]
    resources :comments, only: %i[index destroy]
    resources :inquiries, only: %i[index show destroy] do
      member do
        post :close
      end
    end
  end

  root 'guide#about'
  resources :users, only: %i[new create show edit update]
  get '/login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'

  resources :vtubers, only: %i[show index]
  resources :songs, only: %i[new create index show edit update destroy] do
    resources :comments, only: %i[create destroy]
    resources :favorites, only: %i[create destroy]
    collection do
      get :favorites
      get :autocomplete
    end
  end
  resources :requests, only: %i[new create] do
    collection do
      post 'vtuber_form'
      post 'song_form'
      get :autocomplete
    end
  end
  
  resources :inquiries, only: %i[new create]

  get '/about', to: 'guide#about'
  get '/terms', to: 'guide#terms'
  get '/privacy_policy', to: 'guide#privacy_policy'

  resources :password_resets, only: %i[new create edit update]
end

app/models/vtuber.rb
class Vtuber < ApplicationRecord
  has_many :songs, dependent: :destroy
  belongs_to :member
  has_many :vtuber_instruments, dependent: :destroy
  has_many :instruments, through: :vtuber_instruments

  validates :channel_name, presence: true, uniqueness: true
  validates :channel_url, presence: true, uniqueness: true

  scope :search_by_name_channel_name, ->(key_words) {
    conditions = key_words.map { |word| "(channel_name ILIKE ? OR name ILIKE ?)" }.join(' AND ')
    where(conditions, *Array.new(key_words.size * 2) { |i| "%#{key_words[i / 2]}%" })
  }
end

app/controllers/admin/vtubers_controller.rb
class Admin::VtubersController < Admin::BaseController
  include Admin::VtubersHelper
  before_action :set_vtuber, only: %i[show edit update destroy]
  before_action :set_members, only: %i[new edit]
  before_action :set_instruments, only: %i[new edit]
  
  def new
    @vtuber = Vtuber.new
  end

  def create
    @vtuber = Vtuber.new(vtuber_params)
    if @vtuber.save
      flash[:success] = t('.success')
      redirect_to admin_vtubers_path
    else
      flash[:danger] = @vtuber.errors.full_messages
      redirect_to action: :new
    end
  end

  def index
    @vtubers = if search_params[:search].present?
                 search_vtubers(search_params[:search])
               else
                 Vtuber.all.order(created_at: :desc).page(params[:page])
               end
  end

  def show; end

  def edit; end

  def update
    if @vtuber.update(vtuber_params)
      redirect_to admin_vtubers_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @vtuber.destroy!
    redirect_to admin_vtubers_path, success: t('.success')
  end

  private

  def set_vtuber
    @vtuber = Vtuber.find(params[:id])
  end

  def set_members
    @members = Member.all
  end

  def set_instruments
    @instruments = Instrument.all
  end

  def vtuber_params
    params.require(:vtuber).permit(:channel_name, :channel_url, :name, :icon, :overview, :member_id, instrument_ids: [])
  end

  def search_params
    params.permit(:search, :channel_name, :name)
  end
end

app/controllers/vtubers_controller.rb
class VtubersController < ApplicationController
  def show
    @vtuber = Vtuber.find(params[:id])
    @songs = @vtuber.songs.order(created_at: :desc).page(params[:page])
  end

  def index
    @vtubers = Vtuber.all.order(created_at: :desc).page(params[:page])
  end
end

app/helpers/admin/vtubers_helper.rb
module Admin::VtubersHelper
  def search_vtubers(search_params)
    key_words = search_params.split(/[\p{blank}\s]+/)
    hiragana = key_words.map { |word| word.tr('ァ-ン', 'ぁ-ん') }
    katakana = key_words.map { |word| word.tr('ぁ-ん', 'ァ-ン') }

    search_vtubers = Vtuber.search_by_name_channel_name(key_words).order(created_at: :desc)
    hiragana_vtubers = Vtuber.search_by_name_channel_name(hiragana).order(created_at: :desc)
    katakana_vtubers = Vtuber.search_by_name_channel_name(katakana).order(created_at: :desc)
    result_vtubers = (search_vtubers + hiragana_vtubers + katakana_vtubers).uniq
    vtubers = Kaminari.paginate_array(result_vtubers).page(params[:page]).per(20)
  end
end

app/helpers/vtubers_helper.rb
module VtubersHelper
end

app/views/admin/vtubers/_vtuber.html.erb
<tr>
  <td>
    <%= vtuber.id %>
  </td>
  <td>
    <%= vtuber.channel_name %>
  </td>
  <td>
    <%= vtuber.channel_url %>
  </td>
  <td>
    <%= vtuber.name %>
  </td>
  <td>
    <%= image_tag vtuber.icon, class: 'brand-image img-circle elevation-3', style: 'width: 50px; height: 50px;' %>
  </td>
  <td>
    <%= l vtuber.created_at, format: :long %>
  </td>
  <td class="d-flex">
    <%= link_to t('defaults.show'), admin_vtuber_path(vtuber), class: 'btn btn-info' %>
    <%= link_to t('defaults.edit'), edit_admin_vtuber_path(vtuber), class: 'btn btn-success' %>
    <%= button_to t('defaults.delete'), admin_vtuber_path(vtuber), method: :delete, data: { turbo_confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/vtubers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= form_with model: @vtuber, url: admin_vtuber_path(@vtuber), local: true do |f| %>
        <%= render 'layouts/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :channel_name %>
          <%= f.text_field :channel_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :channel_url %>
          <%= f.text_field :channel_url, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :icon %>
          <%= f.text_field :icon, id: 'iconUrlInput', class: 'form-control' %>
        </div>
        <div class='mt-3 mb-3'>
          <%= image_tag @vtuber.icon,
                        class: 'rounded-circle',
                        id: 'preview',
                        size: '100x100' %>
        </div>
        <div class="form-group">
          <%= f.label :overview %>
          <%= f.text_area :overview, class: 'form-control', rows: 5, cols: 40 %>
        </div>
        <div class="form-group">
          <%= f.label :member %>
          <%= f.select :member_id, @members.map { |m| [m.name, m.id] }, { prompt: "選択してください" }, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :instrument_id, class: "control-label" %><br>
          <button id="toggleCheckbox" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="btn btn-primary"><%= t('.instruments_list') %></span>
          </button>

          <div id="checkboxWrapper" class="checkbox-wrapper" style="display: none;">
            <%= f.collection_check_boxes(:instrument_ids, Instrument.all, :id, :name) do |b| %>
              <div class="checkbox-item">
                <%= b.check_box(class: "form-control2") %>
                <%= b.label { b.text } %>
              </div>
            <% end %>
          </div>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var iconInput = document.getElementById('iconUrlInput');
    var previewImage = document.getElementById('preview');
    
    previewImage.src = iconInput.value;

    iconInput.addEventListener('input', function() {
      previewImage.src = this.value;
    });
  });
  
  document.getElementById("toggleCheckbox").addEventListener("click", function() {
    var checkboxWrapper = document.getElementById("checkboxWrapper");
    checkboxWrapper.style.display = (checkboxWrapper.style.display === "none") ? "block" : "none";
  });
</script>

app/views/admin/vtubers/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <div class="table-responsive">
          <%= render 'admin/layouts/search_form', url: admin_vtubers_path %>
          <table class="table table-striped">
            <thead>
            <tr>
              <th scope="col">Id</th>
              <th scope="col"><%= t('.channel_name') %></th>
              <th scope="col"><%= t('.channel_url') %></th>
              <th scope="col"><%= t('.name') %></th>
              <th scope="col"><%= t('.icon') %></th>
              <th scope="col"><%= t('.created_at') %></th>
              <th scope="col"><%= link_to t('defaults.vtuber_register'), new_admin_vtuber_path, class: 'btn btn-primary text-center' %></th>
            </tr>
            </thead>
            <tbody>
              <%= render @vtubers %>
            </tbody>
          </table>
          <div class="item__paginate">
            <%= paginate @vtubers %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/vtubers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= form_with model: [:admin, @vtuber], local: true do |f| %>
        <%= render 'layouts/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :channel_name %>
          <%= f.text_field :channel_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :channel_url %>
          <%= f.text_field :channel_url, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :icon %>
          <%= f.text_field :icon, id: 'iconUrlInput', class: 'form-control' %>
        </div>
        <div class='mt-3 mb-3'>
          <%= image_tag 'music_rabbit.jpg',
                        class: 'rounded-circle',
                        id: 'preview',
                        size: '100x100' %>
        </div>
        <div class="form-group">
          <%= f.label :overview %>
          <%= f.text_area :overview, class: 'form-control', rows: 5, cols: 40 %>
        </div>
        <div class="form-group">
          <%= f.label :member %>
          <%= f.select :member_id, @members.map { |m| [m.name, m.id] }, { prompt: "選択してください" }, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :instrument_id, class: "control-label" %><br>
          <button id="toggleCheckbox" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="btn btn-primary"><%= t('.instruments_list') %></span>
          </button>

          <div id="checkboxWrapper" class="checkbox-wrapper" style="display: none;">
            <%= f.collection_check_boxes(:instrument_ids, Instrument.all, :id, :name) do |b| %>
              <div class="checkbox-item">
                <%= b.check_box(class: "form-control2") %>
                <%= b.label { b.text } %>
              </div>
            <% end %>
          </div>
        </div>
        <%= f.submit t('defaults.register'), class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var iconInput = document.getElementById('iconUrlInput');
    var previewImage = document.getElementById('preview');
    
    previewImage.src = iconInput.value;

    iconInput.addEventListener('input', function() {
      previewImage.src = this.value;
    });
  });
  
  document.getElementById("toggleCheckbox").addEventListener("click", function() {
    var checkboxWrapper = document.getElementById("checkboxWrapper");
    checkboxWrapper.style.display = (checkboxWrapper.style.display === "none") ? "block" : "none";
  });
</script>

app/views/admin/vtubers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <div class="d-flex">
        <%= link_to t('defaults.edit'), edit_admin_vtuber_path(@vtuber), class: 'btn btn-success' %>
        <%= button_to t('defaults.delete'), admin_vtuber_path(@vtuber), method: :delete, data: { turbo_confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"style="width: 150px;">Id</th>
          <td><%= @vtuber.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= t('.channel_name') %></th>
          <td><%= @vtuber.channel_name %></td>
        </tr>
        <tr>
          <th scope="row"><%= t('.channel_url') %></th>
          <td><%= @vtuber.channel_url %></td>
        </tr>
        <tr>
          <th scope="row"><%= t('.name') %></th>
          <td><%= @vtuber.name %></td>
        </tr>
        <tr>
          <th scope="row"><%= t('.overview') %></th>
          <td><%= @vtuber.overview %></td>
        </tr>
        <tr>
          <th scope="row"><%= t('.instrument') %></th>
          <td>
            <% if @vtuber.instruments.any? %>
              <%= @vtuber.instruments.map(&:name).join(', ') %>
            <% else %>
            <%= t('.not_instrument') %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th scope="row"><%= t('.created_at') %></th>
          <td><%= l @vtuber.created_at, format: :long %></td>
        </tr>
      </table>
    </div>
  </div>
</div>