config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index show edit update destroy]
    resources :vtubers, only: %i[new create index show edit update destroy]
    resources :instruments, only: %i[new create]
    resources :members, only: %i[new create index destroy]
    resources :songs, only: %i[new create index show edit update destroy]
    resources :comments, only: %i[index destroy]
    resources :inquiries, only: %i[index show destroy] do
      member do
        post :close
      end
    end
  end

  root 'guide#about'
  resources :users, only: %i[new create show edit update]
  get '/login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'

  resources :vtubers, only: %i[show index]
  resources :songs, only: %i[new create index show edit update destroy] do
    resources :comments, only: %i[create destroy]
    resources :favorites, only: %i[create destroy]
    collection do
      get :favorites
      get :autocomplete
    end
  end
  resources :requests, only: %i[new create] do
    collection do
      post 'vtuber_form'
      post 'song_form'
      get :autocomplete
    end
  end
  
  resources :inquiries, only: %i[new create]

  get '/about', to: 'guide#about'
  get '/terms', to: 'guide#terms'
  get '/privacy_policy', to: 'guide#privacy_policy'

  resources :password_resets, only: %i[new create edit update]
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :request_instruments, dependent: :destroy
  has_many :instruments, through: :request_instruments

  enum category: { 'Vtuber': 0, '歌': 1 } 

  validates :category, presence: true
  validates :name, presence: true
  validates :url, presence: true, uniqueness: true
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  include RequestsHelper
  before_action :set_instruments, only: %i[new]
  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    @request.user_id = current_user.id
    if @request.save
      respond_to(&:html)
      redirect_to new_request_path, success: t('.success')
    else
      respond_to(&:turbo_stream)
      render turbo_stream: turbo_stream.replace('request_form', partial: 'requests/vtuber', locals: { request: @request }), status: :unprocessable_entity
    end
  end

  def vtuber_form
    @request = Request.new
    puts @request.inspect
    respond_to(&:turbo_stream) 
    render turbo_stream: turbo_stream.update('request_form', partial: 'requests/vtuber', locals: { request: @request }), status: :unprocessable_entity
  end

  def song_form
    @request = Request.new
    respond_to(&:turbo_stream) 
    render turbo_stream: turbo_stream.update('request_form', partial: 'requests/song', locals: { request: @request }), status: :unprocessable_entity
  end

  def autocomplete
    @results = search_autocomplete(params[:q])

    respond_to(&:js)
  end

  private

  def request_params
    params.require(:request).permit(:user_id, :category, :name, :url, :member_name, instrument_ids: [])
  end

  def set_instruments
    @instruments = Instrument.all
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
  def search_autocomplete(search_params)
    hiragana = search_params.tr('ァ-ン', 'ぁ-ん')
    katakana = search_params.tr('ぁ-ん', 'ァ-ン')

    search_names = Member.search_by_name(search_params).pluck(:name).flatten.uniq
    hiragana_names = Member.search_by_name(hiragana).pluck(:name).flatten.uniq
    katakana_names = Member.search_by_name(katakana).pluck(:name).flatten.uniq
    results = (search_names + hiragana_names + katakana_names).uniq.take(20)
  end
end

app/views/requests/_song.html.erb
<turbo-frame id="request_form">
  <%= render 'layouts/flash_messages' %>
  <%= render 'layouts/error_messages', object: @request %>
  <h1 class="app-title"><%= t('.title') %></h1>
  <%= button_to t('.change_request'), vtuber_form_requests_path, remote: true, data: { turbo_frame: "request_form" }, class: 'btn btn-primary' %>
  <%= form_with model: @request, local: true do |f| %>
    <div class="form-group">
      <%= f.label :category %>
      <%= f.text_field :category, value: "歌", readonly: true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url, class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.submit t('defaults.register'), class: 'btn btn-primary' %>
    </div>
  <% end %>
</turbo-frame>

app/views/requests/_vtuber.html.erb
<turbo-frame id="request_form">
  <%= render 'layouts/flash_messages' %>
  <%= render 'layouts/error_messages', object: @request %>
  <h1 class="app-title"><%= t('.title') %></h1>
  <%= button_to t('.change_request'), song_form_requests_path, remote: true, data: { turbo_frame: "request_form" }, class: 'btn btn-primary' %>
  <%= form_with model: @request, local: true do |f| %>
    <div class="form-group">
      <%= f.label :category %>
      <%= f.text_field :category, value: "Vtuber", readonly: true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url, class: 'form-control' %>
    </div>
    <div class="mb-3" data-controller="autocomplete" data-autocomplete-url-value="/requests/autocomplete" role="combobox">
      <div class="form-group">
        <%= f.label :member_name %>
        <%= f.text_field :member_name, class: 'form-control', value: params[:member_name], data: { autocomplete_target: 'input' } %>
      </div>
      <ul class="list-group" data-autocomplete-target="results"></ul>
    </div>
    <div class="form-group">
      <%= f.label :instrument_ids, class: "control-label" %><br>
      <button id="toggleCheckbox" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="btn btn-primary"><%= t('.instruments_list') %></span>
      </button>

      <div id="checkboxWrapper" class="checkbox-wrapper" style="display: none;">
        <%= f.collection_check_boxes(:instrument_ids, Instrument.all, :id, :name) do |b| %>
          <div class="checkbox-item">
            <%= b.check_box(class: "form-control2") %>
            <%= b.label { b.text } %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="mb-3">
      <%= f.submit t('defaults.register'), class: 'btn btn-primary' %>
    </div>
  <% end %>

  <script>
    document.getElementById("toggleCheckbox").addEventListener("click", function() {
      var checkboxWrapper = document.getElementById("checkboxWrapper");
      checkboxWrapper.style.display = (checkboxWrapper.style.display === "none") ? "block" : "none";
    });
  </script>
</turbo-frame>

app/views/requests/autocomplete.js.erb
<% @results.each do |result| %>
  <li class="list-group-item" role="option" data-autocomplete-value="<%= result %>">
    <%= result %>
  </li>
<% end %>

app/views/requests/new.html.erb
<div class="container">
  <div class="row">
    <div class="mt-3">
      <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
        <turbo-frame id="request_form">
          <%= render 'vtuber' %>
        </turbo-frame>
      </div>
    </div>
  </div>
</div>